/**:
  controller_manager:
    ros__parameters:
      update_rate: 100 # Hz

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      mobile_base_controller:
        type: diff_drive_controller/DiffDriveController

      arm_right_controller:
        type: joint_trajectory_controller/JointTrajectoryController

      arm_left_controller:
        type: joint_trajectory_controller/JointTrajectoryController

      torso_controller:
        type: joint_trajectory_controller/JointTrajectoryController

      head_controller:
        type: joint_trajectory_controller/JointTrajectoryController

  mobile_base_controller:
    ros__parameters:
      left_wheel_names:
        - left_wheel
      right_wheel_names:
        - right_wheel
      wheel_separation: 0.53
      wheel_radius: 0.1
      wheel_separation_multiplier: 1.0
      left_wheel_radius_multiplier: 1.0
      right_wheel_radius_multiplier: 1.0
      odom_frame_id: odom
      base_frame_id: base
      pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
      twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
      position_feedback: false
      open_loop: false
      enable_odom_tf: true
      cmd_vel_timeout: 0.5
      publish_limited_velocity: true
      velocity_rolling_window_size: 10
      linear.x.max_velocity: 1
      linear.x.min_velocity: -1
      linear.x.max_acceleration: 0.5
      linear.x.max_deceleration: -0.5
      linear.x.max_acceleration_reverse: -0.5
      linear.x.max_deceleration_reverse: 0.5
      linear.x.max_jerk: .NAN
      linear.x.min_jerk: .NAN
      angular.z.max_velocity: 0.8
      angular.z.min_velocity: -0.8
      angular.z.max_acceleration: 1.0
      angular.z.max_deceleration: -1.0
      angular.z.max_acceleration_reverse: -1.0
      angular.z.max_deceleration_reverse: 1.0
      angular.z.max_jerk: .NAN
      angular.z.min_jerk: .NAN

  arm_right_controller:
    ros__parameters:
      joints:
        - right_arm_0
        - right_arm_1
        - right_arm_2
        - right_arm_3
        - right_arm_4
        - right_arm_5
        - right_arm_6
        - right_trigger
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      allow_nonzero_velocity_at_trajectory_end: true
      allow_partial_joints_goal: true
      interpolate_from_desired_state: true

  arm_left_controller:
    ros__parameters:
      joints:
        - left_arm_0
        - left_arm_1
        - left_arm_2
        - left_arm_3
        - left_arm_4
        - left_arm_5
        - left_arm_6
        - left_trigger
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      allow_nonzero_velocity_at_trajectory_end: true
      allow_partial_joints_goal: true
      interpolate_from_desired_state: true

  torso_controller:
    ros__parameters:
      joints:
        - torso_0
        - torso_1
        - torso_2
        - torso_3
        - torso_4
        - torso_5
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      allow_nonzero_velocity_at_trajectory_end: true
      allow_partial_joints_goal: true
      interpolate_from_desired_state: true

  head_controller:
    ros__parameters:
      joints:
        - head_0
        - head_1
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      allow_nonzero_velocity_at_trajectory_end: true
      allow_partial_joints_goal: true
      interpolate_from_desired_state: true
