/**:
  controller_manager:
    ros__parameters:
      update_rate: 100
      body_joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
      hand_left_joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
      hand_right_joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
      mobile_base_controller:
        type: mecanum_drive_controller/MecanumDriveController
      arm_right_controller:
        type: joint_trajectory_controller/JointTrajectoryController
      arm_left_controller:
        type: joint_trajectory_controller/JointTrajectoryController
      torso_controller:
        type: joint_trajectory_controller/JointTrajectoryController
      head_controller:
        type: joint_trajectory_controller/JointTrajectoryController
      hand_left_controller:
        type: joint_trajectory_controller/JointTrajectoryController
      hand_right_controller:
        type: joint_trajectory_controller/JointTrajectoryController
  body_joint_state_broadcaster:
    ros__parameters:
      joints:
      - wheel_fr
      - wheel_fl
      - wheel_rr
      - wheel_rl
      - torso_0
      - torso_1
      - torso_2
      - torso_3
      - torso_4
      - torso_5
      - right_arm_0
      - right_arm_1
      - right_arm_2
      - right_arm_3
      - right_arm_4
      - right_arm_5
      - right_arm_6
      - left_arm_0
      - left_arm_1
      - left_arm_2
      - left_arm_3
      - left_arm_4
      - left_arm_5
      - left_arm_6
      - head_0
      - head_1
      interfaces:
      - position
      - velocity
      - effort
  hand_left_joint_state_broadcaster:
    ros__parameters:
      joints:
      - left_finger1_joint1
      - left_finger1_joint2
      - left_finger1_joint3
      - left_finger1_joint4
      - left_finger2_joint1
      - left_finger2_joint2
      - left_finger2_joint3
      - left_finger2_joint4
      - left_finger3_joint1
      - left_finger3_joint2
      - left_finger3_joint3
      - left_finger3_joint4
      - left_finger4_joint1
      - left_finger4_joint2
      - left_finger4_joint3
      - left_finger4_joint4
      - left_finger5_joint1
      - left_finger5_joint2
      - left_finger5_joint3
      - left_finger5_joint4
      interfaces:
      - position
      - velocity
      - effort
  hand_right_joint_state_broadcaster:
    ros__parameters:
      joints:
      - right_finger1_joint1
      - right_finger1_joint2
      - right_finger1_joint3
      - right_finger1_joint4
      - right_finger2_joint1
      - right_finger2_joint2
      - right_finger2_joint3
      - right_finger2_joint4
      - right_finger3_joint1
      - right_finger3_joint2
      - right_finger3_joint3
      - right_finger3_joint4
      - right_finger4_joint1
      - right_finger4_joint2
      - right_finger4_joint3
      - right_finger4_joint4
      - right_finger5_joint1
      - right_finger5_joint2
      - right_finger5_joint3
      - right_finger5_joint4
      interfaces:
      - position
      - velocity
      - effort
  mobile_base_controller:
    ros__parameters:
      reference_timeout: 0.5
      front_left_wheel_command_joint_name: wheel_fl
      front_right_wheel_command_joint_name: wheel_fr
      rear_right_wheel_command_joint_name: wheel_rr
      rear_left_wheel_command_joint_name: wheel_rl
      kinematics:
        base_frame_offset:
          x: 0.0
          y: 0.0
          theta: 0.0
        wheels_radius: 0.076
        sum_of_robot_center_projection_on_X_Y_axis: 0.49
      odom_frame_id: odom
      base_frame_id: base
      enable_odom_tf: true
      pose_covariance_diagonal:
      - 0.001
      - 0.001
      - 0.001
      - 0.001
      - 0.001
      - 0.01
      twist_covariance_diagonal:
      - 0.001
      - 0.001
      - 0.001
      - 0.001
      - 0.001
      - 0.01
  arm_right_controller:
    ros__parameters:
      joints:
      - right_arm_0
      - right_arm_1
      - right_arm_2
      - right_arm_3
      - right_arm_4
      - right_arm_5
      - right_arm_6
      command_interfaces:
      - position
      state_interfaces:
      - position
      - velocity
      allow_nonzero_velocity_at_trajectory_end: true
      allow_partial_joints_goal: true
      interpolate_from_desired_state: true
  arm_left_controller:
    ros__parameters:
      joints:
      - left_arm_0
      - left_arm_1
      - left_arm_2
      - left_arm_3
      - left_arm_4
      - left_arm_5
      - left_arm_6
      command_interfaces:
      - position
      state_interfaces:
      - position
      - velocity
      allow_nonzero_velocity_at_trajectory_end: true
      allow_partial_joints_goal: true
      interpolate_from_desired_state: true
  torso_controller:
    ros__parameters:
      joints:
      - torso_0
      - torso_1
      - torso_2
      - torso_3
      - torso_4
      - torso_5
      command_interfaces:
      - position
      state_interfaces:
      - position
      - velocity
      allow_nonzero_velocity_at_trajectory_end: true
      allow_partial_joints_goal: true
      interpolate_from_desired_state: true
  head_controller:
    ros__parameters:
      joints:
      - head_0
      - head_1
      command_interfaces:
      - position
      state_interfaces:
      - position
      - velocity
      allow_nonzero_velocity_at_trajectory_end: true
      allow_partial_joints_goal: true
      interpolate_from_desired_state: true
  hand_left_controller:
    ros__parameters:
      joints:
      - left_finger1_joint1
      - left_finger1_joint2
      - left_finger1_joint3
      - left_finger1_joint4
      - left_finger2_joint1
      - left_finger2_joint2
      - left_finger2_joint3
      - left_finger2_joint4
      - left_finger3_joint1
      - left_finger3_joint2
      - left_finger3_joint3
      - left_finger3_joint4
      - left_finger4_joint1
      - left_finger4_joint2
      - left_finger4_joint3
      - left_finger4_joint4
      - left_finger5_joint1
      - left_finger5_joint2
      - left_finger5_joint3
      - left_finger5_joint4
      command_interfaces:
      - position
      state_interfaces:
      - position
      - velocity
      allow_nonzero_velocity_at_trajectory_end: true
      allow_partial_joints_goal: true
      interpolate_from_desired_state: true
  hand_right_controller:
    ros__parameters:
      joints:
      - right_finger1_joint1
      - right_finger1_joint2
      - right_finger1_joint3
      - right_finger1_joint4
      - right_finger2_joint1
      - right_finger2_joint2
      - right_finger2_joint3
      - right_finger2_joint4
      - right_finger3_joint1
      - right_finger3_joint2
      - right_finger3_joint3
      - right_finger3_joint4
      - right_finger4_joint1
      - right_finger4_joint2
      - right_finger4_joint3
      - right_finger4_joint4
      - right_finger5_joint1
      - right_finger5_joint2
      - right_finger5_joint3
      - right_finger5_joint4
      command_interfaces:
      - position
      state_interfaces:
      - position
      - velocity
      allow_nonzero_velocity_at_trajectory_end: true
      allow_partial_joints_goal: true
      interpolate_from_desired_state: true
