/**:
  controller_manager:
    ros__parameters:
      update_rate: 100

      body_joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      hand_left_joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      hand_right_joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      arm_right_controller:
        type: joint_trajectory_controller/JointTrajectoryController

      arm_left_controller:
        type: joint_trajectory_controller/JointTrajectoryController

      torso_controller:
        type: joint_trajectory_controller/JointTrajectoryController

      leg_controller:
        type: joint_trajectory_controller/JointTrajectoryController

      hand_left_controller:
        type: joint_trajectory_controller/JointTrajectoryController

      hand_right_controller:
        type: joint_trajectory_controller/JointTrajectoryController

  body_joint_state_broadcaster:
    ros__parameters:
      joints:
        - left_hip_pitch_joint
        - left_hip_roll_joint
        - left_hip_yaw_joint
        - left_knee_joint
        - left_ankle_pitch_joint
        - left_ankle_roll_joint
        - right_hip_pitch_joint
        - right_hip_roll_joint
        - right_hip_yaw_joint
        - right_knee_joint
        - right_ankle_pitch_joint
        - right_ankle_roll_joint
        - waist_yaw_joint
        - waist_roll_joint
        - waist_pitch_joint
        - left_shoulder_pitch_joint
        - left_shoulder_roll_joint
        - left_shoulder_yaw_joint
        - left_elbow_joint
        - left_wrist_roll_joint
        - left_wrist_pitch_joint
        - left_wrist_yaw_joint
        - right_shoulder_pitch_joint
        - right_shoulder_roll_joint
        - right_shoulder_yaw_joint
        - right_elbow_joint
        - right_wrist_roll_joint
        - right_wrist_pitch_joint
        - right_wrist_yaw_joint
      interfaces:
        - position
        - velocity
        - effort

  hand_left_joint_state_broadcaster:
    ros__parameters:
      joints:
        - l_ih_thumb_proximal_yaw
        - l_ih_thumb_proximal_pitch
        - l_ih_index_proximal
        - l_ih_middle_proximal
        - l_ih_ring_proximal
        - l_ih_pinky_proximal
      interfaces:
        - position
        - velocity
        - effort

  hand_right_joint_state_broadcaster:
    ros__parameters:
      joints:
        - r_ih_thumb_proximal_yaw
        - r_ih_thumb_proximal_pitch
        - r_ih_index_proximal
        - r_ih_middle_proximal
        - r_ih_ring_proximal
        - r_ih_pinky_proximal
      interfaces:
        - position
        - velocity
        - effort

  arm_right_controller:
    ros__parameters:
      joints:
        - right_shoulder_pitch_joint
        - right_shoulder_roll_joint
        - right_shoulder_yaw_joint
        - right_elbow_joint
        - right_wrist_roll_joint
        - right_wrist_pitch_joint
        - right_wrist_yaw_joint
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      allow_nonzero_velocity_at_trajectory_end: true
      allow_partial_joints_goal: true
      interpolate_from_desired_state: true

  arm_left_controller:
    ros__parameters:
      joints:
        - left_shoulder_pitch_joint
        - left_shoulder_roll_joint
        - left_shoulder_yaw_joint
        - left_elbow_joint
        - left_wrist_roll_joint
        - left_wrist_pitch_joint
        - left_wrist_yaw_joint
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      allow_nonzero_velocity_at_trajectory_end: true
      allow_partial_joints_goal: true
      interpolate_from_desired_state: true

  torso_controller:
    ros__parameters:
      joints:
        - waist_yaw_joint
        - waist_roll_joint
        - waist_pitch_joint
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      allow_nonzero_velocity_at_trajectory_end: true
      allow_partial_joints_goal: true
      interpolate_from_desired_state: true

  leg_controller:
    ros__parameters:
      joints:
        - left_hip_pitch_joint
        - left_hip_roll_joint
        - left_hip_yaw_joint
        - left_knee_joint
        - left_ankle_pitch_joint
        - left_ankle_roll_joint
        - right_hip_pitch_joint
        - right_hip_roll_joint
        - right_hip_yaw_joint
        - right_knee_joint
        - right_ankle_pitch_joint
        - right_ankle_roll_joint
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      allow_nonzero_velocity_at_trajectory_end: true
      allow_partial_joints_goal: true
      interpolate_from_desired_state: true

  hand_left_controller:
    ros__parameters:
      joints:
        - l_ih_thumb_proximal_yaw
        - l_ih_thumb_proximal_pitch
        - l_ih_index_proximal
        - l_ih_middle_proximal
        - l_ih_ring_proximal
        - l_ih_pinky_proximal
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      allow_nonzero_velocity_at_trajectory_end: true
      allow_partial_joints_goal: true
      interpolate_from_desired_state: true

  hand_right_controller:
    ros__parameters:
      joints:
        - r_ih_thumb_proximal_yaw
        - r_ih_thumb_proximal_pitch
        - r_ih_index_proximal
        - r_ih_middle_proximal
        - r_ih_ring_proximal
        - r_ih_pinky_proximal
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      allow_nonzero_velocity_at_trajectory_end: true
      allow_partial_joints_goal: true
      interpolate_from_desired_state: true
