initial_positions:
  wheel_fr: 0
  wheel_fl: 0
  wheel_rr: 0
  wheel_rl: 0
  torso_0: 0
  torso_1: 0
  torso_2: 0
  torso_3: 0
  torso_4: 0
  torso_5: 0
  right_arm_0: 0
  right_arm_1: 0
  right_arm_2: 0
  right_arm_3: 0
  right_arm_4: 0
  right_arm_5: 0
  right_arm_6: 0
  left_arm_0: 0
  left_arm_1: 0
  left_arm_2: 0
  left_arm_3: 0
  left_arm_4: 0
  left_arm_5: 0
  left_arm_6: 0
  head_0: 0
  head_1: 0
  right_finger1_joint1: 0
  right_finger1_joint2: 0
  right_finger1_joint3: 0
  right_finger1_joint4: 0
  right_finger2_joint1: 0
  right_finger2_joint2: 0
  right_finger2_joint3: 0
  right_finger2_joint4: 0
  right_finger3_joint1: 0
  right_finger3_joint2: 0
  right_finger3_joint3: 0
  right_finger3_joint4: 0
  right_finger4_joint1: 0
  right_finger4_joint2: 0
  right_finger4_joint3: 0
  right_finger4_joint4: 0
  right_finger5_joint1: 0
  right_finger5_joint2: 0
  right_finger5_joint3: 0
  right_finger5_joint4: 0
  left_finger1_joint1: 0
  left_finger1_joint2: 0
  left_finger1_joint3: 0
  left_finger1_joint4: 0
  left_finger2_joint1: 0
  left_finger2_joint2: 0
  left_finger2_joint3: 0
  left_finger2_joint4: 0
  left_finger3_joint1: 0
  left_finger3_joint2: 0
  left_finger3_joint3: 0
  left_finger3_joint4: 0
  left_finger4_joint1: 0
  left_finger4_joint2: 0
  left_finger4_joint3: 0
  left_finger4_joint4: 0
  left_finger5_joint1: 0
  left_finger5_joint2: 0
  left_finger5_joint3: 0
  left_finger5_joint4: 0
