initial_positions:
  lift_joint: 0.0
  head_joint1: 0.0
  head_joint2: 0.0
  arm_l_joint1: 0.0
  arm_l_joint2: 0.0
  arm_l_joint3: 0.0
  arm_l_joint4: -0.7
  arm_l_joint5: 0.0
  arm_l_joint6: 0.0
  arm_l_joint7: 0.0
  arm_r_joint1: 0.0
  arm_r_joint2: 0.0
  arm_r_joint3: 0.0
  arm_r_joint4: -0.7
  arm_r_joint5: 0.0
  arm_r_joint6: 0.0
  arm_r_joint7: 0.0
  gripper_l_joint1: 0.0
  gripper_r_joint1: 0.0
  finger_l_joint1: 0.0
  finger_l_joint2: 0.0
  finger_l_joint3: 0.0
  finger_l_joint4: 0.0
  finger_l_joint5: 0.0
  finger_l_joint6: 0.0
  finger_l_joint7: 0.0
  finger_l_joint8: 0.0
  finger_l_joint9: 0.0
  finger_l_joint10: 0.0
  finger_l_joint11: 0.0
  finger_l_joint12: 0.0
  finger_l_joint13: 0.0
  finger_l_joint14: 0.0
  finger_l_joint15: 0.0
  finger_l_joint16: 0.0
  finger_l_joint17: 0.0
  finger_l_joint18: 0.0
  finger_l_joint19: 0.0
  finger_l_joint20: 0.0
  finger_r_joint1: 0.0
  finger_r_joint2: 0.0
  finger_r_joint3: 0.0
  finger_r_joint4: 0.0
  finger_r_joint5: 0.0
  finger_r_joint6: 0.0
  finger_r_joint7: 0.0
  finger_r_joint8: 0.0
  finger_r_joint9: 0.0
  finger_r_joint10: 0.0
  finger_r_joint11: 0.0
  finger_r_joint12: 0.0
  finger_r_joint13: 0.0
  finger_r_joint14: 0.0
  finger_r_joint15: 0.0
  finger_r_joint16: 0.0
  finger_r_joint17: 0.0
  finger_r_joint18: 0.0
  finger_r_joint19: 0.0
  finger_r_joint20: 0.0
  left_wheel_steer_joint: 0.0
  right_wheel_steer_joint: 0.0
  rear_wheel_steer_joint: 0.0
  left_wheel_drive_joint: 0.0
  right_wheel_drive_joint: 0.0
  rear_wheel_drive_joint: 0.0
