initial_positions:
  lift_joint: 0.0
  head_joint1: 0.0
  head_joint2: 0.0
  arm_l_joint1: 0.0
  arm_l_joint2: 0.0
  arm_l_joint3: 0.0
  arm_l_joint4: -0.7
  arm_l_joint5: 0.0
  arm_l_joint6: 0.0
  arm_l_joint7: 0.0
  arm_r_joint1: 0.0
  arm_r_joint2: 0.0
  arm_r_joint3: 0.0
  arm_r_joint4: -0.7
  arm_r_joint5: 0.0
  arm_r_joint6: 0.0
  arm_r_joint7: 0.0
