<?xml version="1.0"?>
<package format="3">
  <name>rb_mujoco_ros2</name>
  <version>0.1.0</version>
  <description>Metapackage for Rainbow Robotics RB-Series MuJoCo simulation.</description>
  <maintainer email="shkwon@tommoro.ai">Sunghyun Kwon</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>rb_mujoco_bringup</exec_depend>
  <exec_depend>rb_mujoco_description</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
