initial_positions:
  left_hip_pitch_joint: 0.0
  left_hip_roll_joint: 0.0
  left_hip_yaw_joint: 0.0
  left_knee_joint: 0.0
  left_ankle_pitch_joint: 0.0
  left_ankle_roll_joint: 0.0
  right_hip_pitch_joint: 0.0
  right_hip_roll_joint: 0.0
  right_hip_yaw_joint: 0.0
  right_knee_joint: 0.0
  right_ankle_pitch_joint: 0.0
  right_ankle_roll_joint: 0.0
  waist_yaw_joint: 0.0
  waist_roll_joint: 0.0
  waist_pitch_joint: 0.0
  left_shoulder_pitch_joint: 0.0
  left_shoulder_roll_joint: 0.0
  left_shoulder_yaw_joint: 0.0
  left_elbow_joint: 0.0
  left_wrist_roll_joint: 0.0
  left_wrist_pitch_joint: 0.0
  left_wrist_yaw_joint: 0.0
  right_shoulder_pitch_joint: 0.0
  right_shoulder_roll_joint: 0.0
  right_shoulder_yaw_joint: 0.0
  right_elbow_joint: 0.0
  right_wrist_roll_joint: 0.0
  right_wrist_pitch_joint: 0.0
  right_wrist_yaw_joint: 0.0
  left_hand_thumb_0_joint: 0.0
  left_hand_thumb_1_joint: 0.0
  left_hand_thumb_2_joint: 0.0
  left_hand_middle_0_joint: 0.0
  left_hand_middle_1_joint: 0.0
  left_hand_index_0_joint: 0.0
  left_hand_index_1_joint: 0.0
  right_hand_thumb_0_joint: 0.0
  right_hand_thumb_1_joint: 0.0
  right_hand_thumb_2_joint: 0.0
  right_hand_middle_0_joint: 0.0
  right_hand_middle_1_joint: 0.0
  right_hand_index_0_joint: 0.0
  right_hand_index_1_joint: 0.0
  l_ih_thumb_proximal_yaw: 0.0
  l_ih_thumb_proximal_pitch: 0.0
  l_ih_index_proximal: 0.0
  l_ih_middle_proximal: 0.0
  l_ih_ring_proximal: 0.0
  l_ih_pinky_proximal: 0.0
  r_ih_thumb_proximal_yaw: 0.0
  r_ih_thumb_proximal_pitch: 0.0
  r_ih_index_proximal: 0.0
  r_ih_middle_proximal: 0.0
  r_ih_ring_proximal: 0.0
  r_ih_pinky_proximal: 0.0
