/**:
  controller_manager:
    ros__parameters:
      update_rate: 100

      body_joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      hand_left_joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      hand_right_joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      arm_right_controller:
        type: joint_trajectory_controller/JointTrajectoryController

      arm_left_controller:
        type: joint_trajectory_controller/JointTrajectoryController

      torso_controller:
        type: joint_trajectory_controller/JointTrajectoryController

      head_controller:
        type: joint_trajectory_controller/JointTrajectoryController

      hand_left_controller:
        type: joint_trajectory_controller/JointTrajectoryController

      hand_right_controller:
        type: joint_trajectory_controller/JointTrajectoryController

      swerve_drive_controller:
        type: ffw_swerve_drive_controller/SwerveDriveController

  body_joint_state_broadcaster:
    ros__parameters:
      joints:
        - lift_joint
        - head_joint1
        - head_joint2
        - arm_l_joint1
        - arm_l_joint2
        - arm_l_joint3
        - arm_l_joint4
        - arm_l_joint5
        - arm_l_joint6
        - arm_l_joint7
        - arm_r_joint1
        - arm_r_joint2
        - arm_r_joint3
        - arm_r_joint4
        - arm_r_joint5
        - arm_r_joint6
        - arm_r_joint7
        - left_wheel_steer_joint
        - right_wheel_steer_joint
        - rear_wheel_steer_joint
        - left_wheel_drive_joint
        - right_wheel_drive_joint
        - rear_wheel_drive_joint
      interfaces:
        - position
        - velocity
        - effort

  hand_left_joint_state_broadcaster:
    ros__parameters:
      joints:
        - gripper_l_joint1
      interfaces:
        - position
        - velocity
        - effort

  hand_right_joint_state_broadcaster:
    ros__parameters:
      joints:
        - gripper_r_joint1
      interfaces:
        - position
        - velocity
        - effort

  arm_right_controller:
    ros__parameters:
      joints:
        - arm_r_joint1
        - arm_r_joint2
        - arm_r_joint3
        - arm_r_joint4
        - arm_r_joint5
        - arm_r_joint6
        - arm_r_joint7
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      allow_nonzero_velocity_at_trajectory_end: true
      allow_partial_joints_goal: true
      interpolate_from_desired_state: true
      set_last_command_interface_value_as_state_on_activation: false

  arm_left_controller:
    ros__parameters:
      joints:
        - arm_l_joint1
        - arm_l_joint2
        - arm_l_joint3
        - arm_l_joint4
        - arm_l_joint5
        - arm_l_joint6
        - arm_l_joint7
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      allow_nonzero_velocity_at_trajectory_end: true
      allow_partial_joints_goal: true
      interpolate_from_desired_state: true
      set_last_command_interface_value_as_state_on_activation: false

  torso_controller:
    ros__parameters:
      joints:
        - lift_joint
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      allow_nonzero_velocity_at_trajectory_end: true
      allow_partial_joints_goal: true
      interpolate_from_desired_state: true
      set_last_command_interface_value_as_state_on_activation: false

  head_controller:
    ros__parameters:
      joints:
        - head_joint1
        - head_joint2
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      allow_nonzero_velocity_at_trajectory_end: true
      allow_partial_joints_goal: true
      interpolate_from_desired_state: true
      set_last_command_interface_value_as_state_on_activation: false

  hand_left_controller:
    ros__parameters:
      joints:
        - gripper_l_joint1
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      allow_nonzero_velocity_at_trajectory_end: true
      allow_partial_joints_goal: true
      interpolate_from_desired_state: true
      set_last_command_interface_value_as_state_on_activation: false

  hand_right_controller:
    ros__parameters:
      joints:
        - gripper_r_joint1
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      allow_nonzero_velocity_at_trajectory_end: true
      allow_partial_joints_goal: true
      interpolate_from_desired_state: true
      set_last_command_interface_value_as_state_on_activation: false

  swerve_drive_controller:
    ros__parameters:
      steering_joint_names:
        - left_wheel_steer_joint
        - right_wheel_steer_joint
        - rear_wheel_steer_joint
      wheel_joint_names:
        - left_wheel_drive_joint
        - right_wheel_drive_joint
        - rear_wheel_drive_joint

      wheel_radius: 0.0865
      module_x_offsets: [0.1371, 0.1371, -0.2899]
      module_y_offsets: [0.2554, -0.2554, 0.0]
      module_angle_offsets: [0.0, 0.0, 0.0]
      module_steering_limit_lower: [-6.28, -6.28, -6.28]
      module_steering_limit_upper: [6.28, 6.28, 6.28]
      module_wheel_speed_limit_lower: [-50.0, -50.0, -50.0]
      module_wheel_speed_limit_upper: [50.0, 50.0, 50.0]

      enabled_steering_angular_velocity_limit: true
      steering_angular_velocity_limit: 100.0
      steering_alignment_angle_error_threshold: 1.0
      steering_alignment_start_angle_error_threshold: 0.01
      steering_alignment_start_speed_error_threshold: 0.1
      enabled_open_loop: false

      cmd_vel_topic: /cmd_vel
      cmd_vel_timeout: 1.0
      odom_solver_method: svd
      odom_source: feedback
      base_frame_id: base_link
      odom_frame_id: odom
      enable_odom_tf: true
      velocity_rolling_window_size: 10
