/**:
  controller_manager:
    ros__parameters:
      update_rate: 100
      body_joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
      arm_controller:
        type: joint_trajectory_controller/JointTrajectoryController

  body_joint_state_broadcaster:
    ros__parameters:
      joints: [base, shoulder, elbow, wrist1, wrist2, wrist3]
      interfaces: [position, velocity, effort]

  arm_controller:
    ros__parameters:
      joints: [base, shoulder, elbow, wrist1, wrist2, wrist3]
      command_interfaces: [position]
      state_interfaces: [position, velocity]
      allow_nonzero_velocity_at_trajectory_end: true
      allow_partial_joints_goal: true
      interpolate_from_desired_state: true
      set_last_command_interface_value_as_state_on_activation: false
