<?xml version="1.0"?>
<package format="3">
  <name>rbpodo_mujoco_bringup</name>
  <version>0.1.0</version>
  <description>Launch files for Rainbow Robotics RB-Series MuJoCo simulation.</description>
  <maintainer email="shkwon@tommoro.ai">Sunghyun Kwon</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend>controller_manager</exec_depend>
  <exec_depend>joint_state_broadcaster</exec_depend>
  <exec_depend>joint_trajectory_controller</exec_depend>
  <exec_depend>rqt_gui</exec_depend>
  <exec_depend>rqt_joint_trajectory_controller</exec_depend>
  <exec_depend>rbpodo_mujoco_description</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
